services:

  search-gov:
    build: 
      context: ../search-gov/
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch7
      - kibana7
      - mysql
      - redis
      - tika
    command: rails server --binding 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ../search-gov/:/usr/src/app
      - gem_cache:/gems
    env_file:
      - ../search-gov/.env/development/app
    networks:
      - app-network

  # Create Dockerfile for both i14y and asis to use these services
  # i14y:
  #   build: 
  #     context: ../i14y/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - elasticsearch7
  #     - kibana7
  #     - mysql
  #     - redis
  #     - tika
  #   command: rails server --binding 0.0.0.0
  #   ports:
  #     - 3300:3000
  #   volumes:
  #     - ../i14y/:/usr/src/app
  #     - gem_cache:/gems

  # asis:
  #   build: 
  #     context: ../asis/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - elasticsearch7
  #     - kibana7
  #     - mysql
  #     - redis
  #     - tika
  #   command: rails server --binding 0.0.0.0
  #   ports:
  #     - 3400:3000
  #   volumes:
  #     - ../asis/:/usr/src/app
  #     - gem_cache:/gems

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.17.7
    depends_on:
      - elasticsearch7
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch7:9200
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - app-network
    command: redis-server --bind "0.0.0.0"

  # Required by search-gov
  tika:
    platform: linux/amd64
    image: apache/tika:2.4.1
    ports:
      - 9998:9998
    networks:
      - app-network

  resque-workers:
    command: 'bundle exec rake environment resque:work'
    build: 
      context: ../search-gov/
    depends_on:
      - elasticsearch7
      - mysql
      - redis
    env_file:
      - ../search-gov/.env/development/app
      - ../search-gov/.env/development/resque
    networks:
      - app-network

  resque-scheduler:
    command: 'bundle exec rake resque:scheduler'
    build:
      context: ../search-gov/
    depends_on:
      - elasticsearch7
      - mysql
      - redis
    env_file:
      - ../search-gov/.env/development/app
      - ../search-gov/.env/development/resque
    networks:
      - app-network

volumes:
  db_data:
  es_7_data:
  gem_cache:

networks:
  app-network:
    driver: bridge
