# searchgov/elasticsearch:7.17.3
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.3
# The following plugins are required for multilingual support in i14y
RUN elasticsearch-plugin install analysis-kuromoji
RUN elasticsearch-plugin install analysis-icu
RUN elasticsearch-plugin install analysis-smartcn
