services:

  elasticsearch7:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch7
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.17.7
    depends_on:
      - elasticsearch7
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch7:9200
    networks:
      - app-network

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - app-network
    command: redis-server --bind "0.0.0.0"

  # Required by search-gov
  tika:
    platform: linux/amd64
    image: apache/tika:2.4.1
    ports:
      - 9998:9998
    networks:
      - app-network

  search-gov:
    platform: linux/amd64/v8
    build: 
      context: ../search-gov/
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch7
      - kibana7
      - mysql
      - redis
      - tika
    command: bin/rails server --binding 0.0.0.0
    ports:
      - 3100:3000
    volumes:
      - ../search-gov/:/usr/src/app
      - gem_cache:/gems
    env_file:
      - ../search-gov/.env/development/app
    networks:
      - app-network
    profiles:
      - search-gov

  resque-workers:
    command: 'bundle exec rake environment resque:work'
    build: 
      context: ../search-gov/
    depends_on:
      - elasticsearch7
      - mysql
      - redis
      - search-gov
    env_file:
      - ../search-gov/.env/development/app
      - ../search-gov/.env/development/resque
    networks:
      - app-network
    profiles:
      - search-gov

  resque-scheduler:
    command: 'bundle exec rake resque:scheduler'
    build:
      context: ../search-gov/
    depends_on:
      - elasticsearch7
      - mysql
      - redis
      - search-gov
    env_file:
      - ../search-gov/.env/development/app
      - ../search-gov/.env/development/resque
    networks:
      - app-network
    profiles:
      - search-gov

  i14y:
    build: 
      context: ../i14y/
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch7
      - kibana7
      - mysql
      - redis
    command: rails server --binding 0.0.0.0
    ports:
      - 3200:3000
    volumes:
      - ../i14y/:/usr/src/app
      - gem_cache:/gems
    networks:
      - app-network
    profiles:
      - i14y
  
  asis:
    build: 
      context: ../asis/
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch7
      - kibana7
      - mysql
      - redis
    command: rails server --binding 0.0.0.0
    ports:
      - 3300:3000
    volumes:
      - ../asis/:/usr/src/app
      - gem_cache:/gems
    networks:
      - app-network
    profiles:
      - asis

volumes:
  db_data:
  es_7_data:
  gem_cache:

networks:
  app-network:
    driver: bridge
