version: '3'

services:
  elasticsearch7:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch7
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=es7-docker-cluster
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch7:9200/_cat/health >/dev/null || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  kibana7:
    image: docker.elastic.co/kibana/kibana:7.17.7
    depends_on:
      - elasticsearch7
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch7:9200
    networks:
      - app-network

  mysql:
    platform: linux/amd64
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    networks:
      - app-network
    command: redis-server --bind "0.0.0.0"

  # Required by search-gov
  tika:
    platform: linux/amd64
    image: apache/tika:2.4.1
    ports:
      - 9998:9998
    networks:
      - app-network

  search-gov:
    platform: linux/amd64
    build:
      context: ../search-gov/
      dockerfile: Dockerfile.dev
    depends_on:
      elasticsearch7:
        condition: service_healthy
      mysql:
        condition: service_started
      redis:
        condition: service_started
      kibana7:
        condition: service_started
      tika:
        condition: service_started
    command: bin/rails server --binding 0.0.0.0 -p 3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ../search-gov/:/usr/src/app
      - gem_cache_search-gov:/gems
    tmpfs:
      - /tmp/pids/
    env_file:
      - ../search-gov/.env.development
    links:
      - i14y
      - asis
      - mysql
      - redis
    networks:
      - app-network
    profiles:
      - search-gov

  resque-workers:
    command: bin/bundle exec rake environment resque:work
    build:
      context: ../search-gov/
      dockerfile: Dockerfile.dev
    depends_on:
      - elasticsearch7
      - mysql
      - redis
      - search-gov
    env_file:
      - ../search-gov/.env.development
    links:
      - i14y
      - asis
      - mysql
      - redis
    networks:
      - app-network
    profiles:
      - search-gov

  resque-scheduler:
    command: bin/bundle exec rake resque:scheduler
    build:
      context: ../search-gov/
      dockerfile: Dockerfile.dev
    depends_on:
      - elasticsearch7
      - mysql
      - redis
      - search-gov
    env_file:
      - ../search-gov/.env.development
      - ../search-gov/.env.test
    links:
      - i14y
      - asis
      - mysql
      - redis
    networks:
      - app-network
    profiles:
      - search-gov

  i14y:
    build:
      context: ../i14y/
      dockerfile: Dockerfile.dev
    depends_on:
      - elasticsearch7
      - kibana7
      - mysql
      - redis
    command: bin/rails server --binding 0.0.0.0 -p 3200
    environment:
      - ES_HOSTS=elasticsearch7:9200
      - PIDFILE=/tmp/pids/server.pid
      - DOCKER=true
    expose:
      - 3200
    tmpfs:
      - /tmp/pids/
    ports:
      - 3200:3200
    volumes:
      - ../i14y/:/usr/src/app
      - ../i14y/config/secrets.yml:/usr/src/app/config/secrets.yml
      - gem_cache_i14y:/gems
    links:
      - elasticsearch7
    networks:
      - app-network
    profiles:
      - i14y

  asis:
    build:
      context: ../asis/
      dockerfile: Dockerfile.dev
    depends_on:
      elasticsearch7:
        condition: service_healthy
    command: bin/rails server --binding 0.0.0.0 -p 3300
    expose:
      - 3300
    ports:
      - 3300:3300
    tmpfs:
      - /tmp/pids/
    environment:
      - PIDFILE=/tmp/pids/server.pid
      - DOCKER=true
    volumes:
      - ../asis/:/usr/src/app
      - ../asis/config/flickr.yml:/usr/src/app/config/flickr.yml
      - gem_cache_asis:/gems
    env_file:
      - ../asis/.env.development
    links:
      - elasticsearch7
    networks:
      - app-network
    profiles:
      - asis

  sidekiq:
    build:
      context: ../asis/
      dockerfile: Dockerfile.dev
    command: bin/bundle exec sidekiq
    depends_on:
      elasticsearch7:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../asis/:/usr/src/app
      - ../asis/config/flickr.yml:/usr/src/app/config/flickr.yml
    env_file:
      - ../asis/.env/development/app
    links:
      - elasticsearch7
    networks:
      - app-network
    profiles:
      - asis

volumes:
  db_data:
  es_7_data:
  gem_cache_i14y:
  gem_cache_asis:
  gem_cache_search-gov:

networks:
  app-network:
    driver: bridge
