# searchgov/elasticsearch:7.17.7
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.7
# The following plugins are required for multilingual search support
RUN elasticsearch-plugin install analysis-kuromoji
RUN elasticsearch-plugin install analysis-icu
RUN elasticsearch-plugin install analysis-smartcn
