# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/base:stable
    # https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          # For the moment and for simplicity, we're just validating the
          # configuration. We will likely want to enhance the test suite
          # to build and run the services, verify the services are running,
          # use a test matrix for multiple OS's, etc.
          name: 'Validate configuration'
          command: docker-compose config --quiet

# https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
      - test
